### ISSUE TITLE
The JAR files

### ISSUE THREAD

**Issue by TomaszKane** [GerritCodeReview/plugins_delete-project#1]
It's a question, not issue:
Any chances to prepare release with jar file like here: https://github.com/davido/gerrit-oauth-provider/releases ?

**Comment by lucamilanesio** [comment]
Have you checked on Gerrit-CI.gerritforge.com? Type delete-project in the search bar and you'll find it :-)

**Comment by TomaszKane** [comment]
Nope, I search:
- here: https://www.google.pl/#q=gerrit+delete+plugin
- here: https://gerrit.googlesource.com/plugins/delete-project/
- here: https://www.gerritcodereview.com/
- here: https://www.google.pl/#q=gerrit+plugin+delete+project+jar+download
- and here: https://github.com/GerritCodeReview/plugins_delete-project

Probably you should do something with that? I believe that most of users start looking from google, official web page or github...

Anyway, thanks for url.

**Comment by lucamilanesio** [comment]
Let me clarify step-by-step:

1. Open your browser and type "https://gerrit-cI.gerritforge.com"
2. The Jenkins console of Gerrit CI is rendered
3. Locate the search bar on the top-right corner, on the left side of of "log in" link
4. Type "delete-project" in the search bar and press enter
5. A list of jobs is rendered 
6. Choose one associated to the Gerrit version (e.g. stable-2.3 for any Gerrit 2.3.x)
7. The page of the Jenkins job to build the "delete-project" plugin is rendered
8. Click on "delete-project.jar" to download the file

I know it is not straightforward, possibly we should look at add a "promotion" step to upload the artifact to GitHub, so that it would be more easily discoverable.

Let me have a look how easy or complex it is 😄 

In the meantime, if you have any issues, please write to the Gerrit Mailing list:
https://groups.google.com/forum/#!forum/repo-discuss

We do not use GitHub as Code Review or collaboration, but instead we use Gerrit Code Review. GitHub is configured simply as "mirror" of the Gerrit projects.

**Comment by TomaszKane** [comment]
Meh, dude, don't trolling...

Yes, my point is "be more easily discoverable" - It's easy I believe to add Gerrit-CI.gerritforge.com link to:
- https://www.gerritcodereview.com/ page
- readme on https://github.com/GerritCodeReview/plugins_delete-project
- https://gerrit.googlesource.com/plugins/

Right? :)

**Comment by lucamilanesio** [comment]
@TomaszKane believe me, I am not trolling, just answering and trying to get things better 👍 

I get your point and I ado agree. 
See below:

- https://github.com/GerritCodeReview/plugins_delete-project/issues/1#issuecomment-258095461 (Link to the CI from www.gerritcodereview.com)
- https://gerrit-review.googlesource.com/90737 (README.md with link to the CI)
- the last one is difficult, because is rendered in the code of the Gitiles plugin ... not editable then :-(

Thanks for your feedback, highly appreciated.

**Comment by lucamilanesio** [comment]
@TomaszKane you have now the link from the Gerrit home page *and* from the plugin's README.md: both are pointing to the CI.
